TEST_CANTONS = {
    'name': 'cantons',
    'description': 'list of cantons of switzerland',
    'columns': [
        {'name': 'canton_id',
         'pk': True,
         'unique': True,
         'dtype': 'num',
         'description': 'canton number'},
        {'name': 'code',
         'dtype': 'str',
         'description': 'cantons official code'},
        {'name': 'name_de',
         'dtype': 'str',
         'description': 'cantons name in german'},
        ],
    'data': [
        [1, "ZH", "Zürich"],
        [2, "BE", "Bern"],
        [3, "LU", "Luzern"],
        [4, "UR", "Uri"],
        [5, "SZ", "Schwyz"],
        [6, "OW", "Obwalden"],
        [7, "NW", "Nidwalden"],
        [8, "GL", "Glarus"],
        [9, "ZG", "Zug"],
        [10, "FR", "Freiburg"],
        [11, "SO", "Solothurn"],
        [12, "BS", "Basel-Stadt"],
        [13, "BL", "Basel-Landschaft"],
        [14, "SH", "Schaffhausen"],
        [15, "AR", "Appenzell Ausserrhoden"],
        [16, "AI", "Appenzell Innerrhoden"],
        [17, "SG", "St.Gallen"],
        [18, "GR", "Graubünden"],
        [19, "AG", "Aargau"],
        [20, "TG", "Thurgau"],
        [21, "TI", "Tessin"],
        [22, "VD", "Waadt"],
        [23, "VS", "Wallis"],
        [24, "NE", "Neuenburg"],
        [25, "GE", "Genf"],
        [26, "JU", "Jura"],
    ]
}
